name: Deploy image to Scaleway

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      TZ: Europe/Paris
      SCW_REGISTRY_ENDPOINT: ${{ vars.SCW_REGISTRY_ENDPOINT }}
      SCW_IMAGE_NAME: ${{ vars.SCW_IMAGE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Lint
       run: npm run lint

      - name: Test (if present)
        run: npm test --if-present
        env:
          NODE_ENV: test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SCW_REGISTRY_ENDPOINT }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.SCW_REGISTRY_ENDPOINT }}/${{ env.SCW_IMAGE_NAME }}:latest
            ${{ env.SCW_REGISTRY_ENDPOINT }}/${{ env.SCW_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
